---
- ansible.builtin.include_role:
    name: opennms-common

- ansible.builtin.include_role:
    name: opennms-icmp

- include_tasks: 01-packages.yml

- name: Configure Java runtime environment
  become_user: opennms
  command: "{{ opennms_home }}/bin/runjava -s"
  tags:
    - opennms
    - initialize

- include_tasks: 10-database-setup.yml

- include_tasks: 20-config.yml

- name: Enable systemd unit for OpenNMS {{ opennms_distribution }}
  ansible.builtin.service:
    name: opennms.service
    enabled: true
  tags:
    - opennms
    - systemd

- name: Start systemd unit for OpenNMS {{ opennms_distribution }}
  ansible.builtin.service:
    name: opennms.service
    state: started
  when:
    - skip_startup | default("false") == "false"
  tags:
    - opennms
    - systemd

- include_tasks: 50-firewall.yml
