# file: opennms-playbook.yml

- hosts: opennms-core
  become: true
  roles:
    - opennms-pgsql
    - opennms-core

- hosts: opennms-minion
  become: true
  roles:
    - opennms-minion

- hosts: opennms-sentinel
  become: true
  roles:
    - opennms-sentinel
