## file: opennms-playbook.yml

- name: Install OpenNMS database
  hosts: database
  become: true
  roles:
    - stub_pgsql

- name: Manage Message broker
  hosts: message-broker
  become: true
  roles:
    - stub_kafka

- name: Manage OpenNMS Horizon Core system
  hosts: core
  become: true
  roles:
    - opennms_core

- name: Manage OpenNMS Horizon Minion
  hosts: minion
  become: true
  roles:
    - opennms_minion

- name: Manage OpenNMS Horizon Sentinel
  hosts: sentinel
  become: true
  roles:
    - opennms_sentinel
