---
- name: Install a Mimir package
  ansible.builtin.apt:
    deb: '{{ mimir_pkg_url }}'
  tags:
    - mimir
    - systemd
- name: Enable and start systemd unit for Mimir
  ansible.builtin.service:
    name: mimir.service
    enabled: true
    state: started
  tags:
    - mimir
    - systemd
