---
- name: Configure time series backend for OpenNMS {{ opennms_distribution }}
  template:
    src: etc/opennms.properties.d/_ansible.timeseries.properties.j2
    dest: "{{ opennms_home }}/etc/opennms.properties.d/_ansible.timeseries.properties"
    owner: opennms
    group: opennms
  with_dict: "{{ opennms_properties_timeseries }}"
  notify:
    - restart opennms
  tags:
    - opennms
    - configuration
