---
- name: Add PostgreSQL signing key to a keyring file
  ansible.builtin.apt_key:
    url: "{{ pgsql_key_url }}"
    keyring: "{{ pgsql_key_ring_file }}"
  tags:
    - opennms
    - postgresql
    - repository

- name: Add PostgreSQL repo to sources list
  ansible.builtin.apt_repository:
    repo: deb [arch={{ arch }} signed-by={{ pgsql_key_ring_file }}] {{ pgsql_repo_url }} {{ ansible_distribution_release }}-pgdg-archive main
    state: present
    update_cache: true
  tags:
    - opennms
    - postgresql
    - repository

- name: Install PostgreSQL Server {{ pg_version }}
  ansible.builtin.package:
    name: postgresql-{{ pg_version }}={{ pg_pkg_version }}
    state: present
  tags:
    - opennms
    - postgresql

- name: Enable and start systemd unit for PostgreSQL
  ansible.builtin.service:
    name: postgresql@{{ pg_version }}-main.service
    enabled: true
    state: started
  tags:
    - opennms
    - postgresql
    - systemd

- name: Install python3-psycopg2 dependency for PostgreSQL community module
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present
  tags:
    - opennms
    - postgresql
    - ansible

- name: Set SCRAM-SHA-256 password encryption
  become_user: postgres
  community.postgresql.postgresql_set:
    name: password_encryption
    value: scram-sha-256
  notify:
    - restart postgresql
  tags:
    - opennms
    - postgresql
    - initialize
    - credentials

- name: Set postgres admin password
  become_user: postgres
  community.postgresql.postgresql_query:
    db: postgres
    query: "ALTER USER {{ postgres_user }} WITH PASSWORD '{{ postgres_password }}';"
  tags:
    - opennms
    - postgresql
    - initialize
    - credentials

- name: Create OpenNMS database user {{ opennms_datasource_db_user }}
  become_user: postgres
  community.postgresql.postgresql_user:
    state: present
    name: "{{ opennms_datasource_db_user }}"
    password: "{{ opennms_datasource_db_password }}"
  tags:
    - opennms
    - postgresql
    - initialize
    - database

- name: Create OpenNMS database {{ opennms_datasource_db_name }}
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ opennms_datasource_db_name }}"
    owner: "{{ opennms_datasource_db_user }}"
  tags:
    - opennms
    - postgresql
    - initialize
    - database
