---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - opennms
    - kafka
    - systemd

- name: Restart kafka
  ansible.builtin.service:
    name: kafka.service
    state: restarted
  tags:
    - opennms
    - kafka
    - systemd
