---
- name: Include OpenNMS Common roles
  ansible.builtin.include_role:
      name: opennms_common

- name: Installing OpenNMS Sentinel
  ansible.builtin.apt:
      name: "opennms-sentinel={{ opennms_pkg_version }}"
      state: present
      install_recommends: false
  tags:
      - opennms
      - sentinel
      - package

- name: Enable systemd unit for OpenNMS Sentinel
  ansible.builtin.service:
      name: sentinel.service
      enabled: true
  tags:
      - opennms
      - sentinel
      - systemd

- name: Start systemd unit for OpenNMS Sentinel
  ansible.builtin.service:
      name: sentinel.service
      state: started
  when:
      - skip_startup | default("false") == "false"
  tags:
      - opennms
      - sentinel
      - systemd
