---
- name: Include OpenNMS OpenJDK roles
  ansible.builtin.include_role:
    name: opennms_openjdk

- name: Set java version to OpenJDK {{ openjdk_version }}
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-{{ openjdk_version }}-openjdk-amd64/bin/java
  tags:
    - opennms
    - kafka
    - java

- name: Create Kafka system user
  ansible.builtin.user:
    comment: Ansible managed system account for Kafka
    name: kafka
    home: "{{ kafka_home }}"
    system: true
    state: present
    shell: /bin/false

- name: Extract Kafka binary
  ansible.builtin.unarchive:
    src: "{{ kafka_url }}"
    dest: /opt
    creates: /opt/kafka_{{ scala_version }}-{{ kafka_version }}/bin
    remote_src: true
    owner: kafka
    group: kafka
  tags:
    - opennms
    - kafka
    - package

- name: Create Kafka log directory
  ansible.builtin.file:
    path: /var/log/kafka
    state: directory
    mode: '0755'
    owner: kafka
    group: kafka

- name: Create Kafka log directory
  ansible.builtin.file:
    path: /var/log/kafka/combined-logs
    state: directory
    mode: '0755'
    owner: kafka
    group: kafka

- name: Configure the Kafka message broker
  ansible.builtin.template:
    src: server.properties.j2
    dest: "{{ kafka_home }}/config/kraft/server.properties"
    owner: kafka
    group: kafka
    mode: "0640"
  with_dict: "{{ kafka_server_properties }}"
  tags:
    - opennms
    - kafka
    - config
  notify:
    - Restart kafka

- name: Verify if Kafka Cluster UUID exists
  ansible.builtin.stat:
    path: "{{ kafka_home }}/ansible_cluster_id"
  register: initialized_cluster_uuid
  tags:
    - opennms
    - kafka
    - config

- name: Generate Cluster UUID
  ansible.builtin.shell: |
    cd {{ kafka_home }}
    bin/kafka-storage.sh random-uuid > ansible_cluster_id
    chown kafka:kafka ansible_cluster_id
    bin/kafka-storage.sh format --ignore-formatted -t $(cat ansible_cluster_id) -c config/kraft/server.properties
  when: not initialized_cluster_uuid.stat.exists
  register: cluster_uuid_output
  changed_when: cluster_uuid_output.rc != 0
  tags:
    - opennms
    - kafka
    - confiig

- name: Install Kafka Systemd unit
  ansible.builtin.template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    mode: '0644'
  notify:
    - Reload systemd
  tags:
    - opennms
    - kafka
    - systemd

- name: Enable systemd unit for Kafka
  ansible.builtin.service:
    name: kafka.service
    enabled: true
  tags:
    - opennms
    - kafka
    - systemd

- name: Start systemd unit for Kafka
  ansible.builtin.service:
    name: kafka.service
    state: started
  when:
    - skip_kafka_startup | default("false") == "false"
  tags:
    - opennms
    - kafka
    - systemd
