---
es_key_url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
es_key_ring_file: /usr/share/keyrings/elasticsearch-keyring.gpg
es_repo_url: https://artifacts.elastic.co/packages/7.x/apt
arch: amd64
es_version: 7.17.9
drift_version: 2.0.5
es_pkg_version: "{{ es_version }}*"
onms_drift_plugin_dir: /usr/share/elasticsearch/plugins/drift
es_etc_dir: /etc/elasticsearch
es_configuration:
  action.destructive_requires_name: true
  bootstrap.memory_lock: true
  # cluster.initial_master_nodes: '["node-1", "node-2"]'
  cluster.max_shards_per_node: 6000
  cluster.name: opennms-flows
  discovery.type: single-node
  # discovery.seed_hosts: '["host1", "host2"]'
  # discovery.zen.minimum_master_nodes: 1
  http.port: 9200
  network.host: 0.0.0.0
  node.attr.rack: r1
  node.name: "{{ ansible_hostname }}"
  node.data: 'true'
  node.ingest: 'true'
  node.master: 'true'
  search.max_buckets: 50000
  path.data: /var/lib/elasticsearch
  path.logs: /var/log/elasticsearch
es_jvm_options: {}
